# Generated by Django 4.2.5 on 2023-11-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='price',
        ),
    ]
