# Generated by Django 4.2.5 on 2023-11-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetype',
            options={'permissions': [('disable_pricetype', 'Can disable price type')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('disable_service', 'Can disable service')]},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'permissions': [('disable_treatment', 'Can disable treatment')]},
        ),
        migrations.AlterModelOptions(
            name='treatmentarea',
            options={'permissions': [('disable_treatmentarea', 'Can disable treatment area')]},
        ),
    ]
