# Generated by Django 4.2.5 on 2023-10-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_remove_pricetype_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='treatmentarea',
            name='deleted_at',
        ),
    ]
