# Generated by Django 4.2.5 on 2023-11-14 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_offer_active', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('offer_image', models.ImageField(upload_to='images/')),
                ('percentage_discount', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'offers',
                'permissions': [('disable_offer', 'Can disable offer')],
            },
        ),
    ]
