# Generated by Django 4.2.5 on 2023-12-02 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_offer_active', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('offer_image', models.ImageField(upload_to='images/', validators=[offers.models.file_size])),
                ('percentage_discount', models.IntegerField(default=None)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treatments.treatment')),
            ],
            options={
                'db_table': 'offers',
                'permissions': [('disable_offer', 'Can disable offer')],
            },
        ),
    ]
