# Generated by Django 4.2.5 on 2023-11-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': [('disable_offer', 'Can disable offer')]},
        ),
    ]
