# Generated by Django 4.2.5 on 2023-11-20 02:21

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_image',
            field=models.ImageField(upload_to='images/', validators=[offers.models.file_size]),
        ),
    ]
