# Generated by Django 4.2.5 on 2023-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
