# Generated by Django 4.2.5 on 2023-10-27 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced_id', models.CharField(default=None, max_length=200)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
