# Generated by Django 4.2.5 on 2023-11-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_code_used',
            field=models.BooleanField(default=False),
        ),
    ]
