# Generated by Django 4.2.5 on 2023-10-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
