# Generated by Django 4.2.5 on 2023-11-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_is_code_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='dicounted_amount',
            new_name='discounted_amount',
        ),
    ]
