# Generated by Django 4.2.5 on 2023-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_price_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='referenced_id',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
