# Generated by Django 4.2.5 on 2023-11-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_price_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
