# Generated by Django 4.2.5 on 2023-11-01 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_redeemed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
