# Generated by Django 4.2.5 on 2023-11-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_offer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='offer_code',
            field=models.CharField(max_length=50),
        ),
    ]
