# Generated by Django 4.2.5 on 2023-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_offer_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('offer_code__isnull', True)), fields=('user', 'offer_code'), name='unique_null'),
        ),
    ]
