# Generated by Django 4.2.5 on 2023-11-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_unique_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_null',
        ),
    ]
