# Generated by Django 4.2.5 on 2023-11-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_transaction_unique_null'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
