# Generated by Django 4.2.5 on 2023-11-17 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[('--:-- --', '--:-- --'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(20, 0), '8:00 PM')])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 17, 13, 1, 48, 571351))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treatments.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'permissions': [('approve_appointment', 'Can approve appointment')],
            },
        ),
    ]
