# Generated by Django 4.2.5 on 2023-11-14 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 22, 9, 35, 551123)),
        ),
    ]
