# Generated by Django 4.2.5 on 2023-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('------', '------'), ('10 AM', '10:00 AM'), ('11 AM', '11:00 AM'), ('12 PM', '12:00 PM'), ('1 PM', '1:00 PM'), ('2 PM', '2:00 PM'), ('3 PM', '3:00 PM'), ('4 PM', '4:00 PM'), ('5 PM', '5:00 PM'), ('6 PM', '6:00 PM'), ('7 PM', '7:00 PM'), ('8 PM', '8:00 PM')], max_length=10),
        ),
    ]
