# Generated by Django 4.2.5 on 2023-12-03 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 4, 57, 40, 734162)),
        ),
    ]
