# Generated by Django 4.2.5 on 2023-11-16 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_created_at_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 2, 56, 48, 673929)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[('------', '------'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM')]),
        ),
    ]
