# Generated by Django 4.2.5 on 2023-11-22 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 21, 35, 32, 378975)),
        ),
    ]
