# Generated by Django 4.2.5 on 2023-10-31 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_renewal_date_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='renewal_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_expiry',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 15, 18, 59, 518132)),
        ),
    ]
