# Generated by Django 4.2.5 on 2023-10-31 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_expiry',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 15, 25, 15, 914194)),
        ),
    ]
