# Generated by Django 4.2.5 on 2023-11-12 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofile_account_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 2, 12, 0, 115711)),
        ),
    ]
