# Generated by Django 4.2.5 on 2023-11-01 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_rename_points_userprofile_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='redeemed_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 9, 14, 20, 808414)),
        ),
    ]
