# Generated by Django 4.2.5 on 2023-11-02 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_remove_userprofile_redeemed_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 1, 14, 52, 18293)),
        ),
    ]
