# Generated by Django 4.2.5 on 2023-11-25 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_alter_userprofile_account_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('disable_user', 'Can disable user'), ('add_patient', 'Can add patient'), ('change_patient', 'Can change patient'), ('view_patient', 'Can view patient'), ('disable_patient', 'Can disable patient'), ('renew_membership', 'Can disable patient'), ('reset_password', 'Can reset patient password'), ('generate_password', 'Can generate patient password'), ('view_analytics', 'Can view analytics')]},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 21, 3, 29, 697571)),
        ),
    ]
