# Generated by Django 4.2.5 on 2023-11-13 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_redeemed', models.DateTimeField(default=django.utils.timezone.now)),
                ('redeemed_points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'redeemed_points',
            },
        ),
    ]
