# Generated by Django 4.2.5 on 2023-11-12 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redeem_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeempoints',
            name='date_redeemed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
